google:
  distance:
    matrix:
      api:
        key: LqFk4b4B4yxDFDP7lXro9VXDKsrBzeRiKz1Aw7wA1PFDmDwvyf3M7DIccek1rrJ8

spring:   
  datasource:
    url: jdbc:mysql://localhost:3306/chofli7al
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        ddl-auto: update
 
  servlet:
     multipart:
         max-file-size: 100MB
         max-request-size: 100MB
